### ISSUE TITLE
Ipv4 resolved back to ipv6

### ISSUE THREAD

**Issue by mplaats** [verdel/powerdns-slave-cleaner#1]
When using the script it reverts van ipv4 of the slave,     to the ipv6 address of the master

command:
/usr/local/bin/powerdns-slave-cleaner --host 1.2.3.4 --port 8081 --api-key xxxxxxx

output:
Error occurred: InvalidURL(Failed to parse: http://0000:000:000:000::3:4:8081/api/v1/servers/localhost/zones)
Error occurred: ConnectionError(('Connection aborted.', RemoteDisconnected('Remote end closed connection without response')))

I obscured the real ip's for security reasons.

**Comment by verdel** [comment]
- The script gets a list of zones on the PowerDNS Slave node
 - Then a list of Master nodes is requested for each zone
 - After that, for each Master node, the presence of zones received from the Slave node is checked

I think this is caused by the fact that one of the `Slave` zones has the IPv6 address of the PowerDNS node as one of the `Master`.

**Comment by mplaats** [comment]
Only the master ip is not in the slave zones. Is it possible to only use ipv4 as the script cannot handle ipv6 in http requests? For example the option to specify the master server next to the slave. This would offer more flexibility.

**Comment by verdel** [comment]
> Only the master ip is not in the slave zones

What do you mean "master ip is not in the slave zones"?

I can ignore IPv6 addresses in master ip list from slave zone information.

I don't think it's a good idea to statically set master addresses via inputs. The point of the utility is that we get for each slave zone the address of the server that serves the Master zone. Then we get a list of zones from the server that serves the Master zone, and if the original Slave zone is missing from the list, then we delete it from the Slave node

**Comment by mplaats** [comment]
Maybe in this case my setup differs, I have an hidden master in my setup. In this case I adjusted the script myself to customise this accordantly to what we need.

**Comment by verdel** [comment]
So if I add `--master-host`, `--master-port`, `--master-api-key` this will fix error for you installation?

**Comment by mplaats** [comment]
That would be perfect!

**Comment by verdel** [comment]
OK. I will try to add this functionality in the next couple of days. Maybe early next week.

**Comment by verdel** [comment]
Can I get a little more detailed information from you about the interaction scheme of your servers?

You said about an hidden master in your setup. Was it meant that you have a zone with the master type on the primary node, which does not have a record about this primary node in the NS record?

And one more clarification. In your case, secondary nodes will always serve slave zones from only one primary node?

Otherwise, I have to take into account that `--master-host` can contain an list of records (there will be additional complexity if the api ports and access keys are different for different primary nodes). If the secondary node has slave zones from several primary nodes, then you need to check the lists of master zones on all primary nodes, otherwise a situation may arise when the slave zone for which the primary node was not correctly specified will be deleted.

**Comment by verdel** [comment]
@mplaats

**Comment by mplaats** [comment]
Yes sure. Sorry for the delay. I have a master where we interface with api to change zone records. And we have 2 slaves that are our authoritives. The api port and keys are the same on all hosts to reduce complexity.

The main bump i ran into in production was that connecting to the slaves was ipv4 but back to the master reverted to ipv6. And listen address was not ipv6 but if so, then the link the tool addresses to make a http connection was wrong also eg http://2001:db8:3333:4444:5555:6666:7777:8888:8081 and not http://[2001:db8:3333:4444:5555:6666:7777:8888]:8081

In my test setup ( ipv4 only and no ipv6 interfaces ) the tool worked just fine. Master had for example 1.2.3.4 and slave 1.2.3.5 so --host 1.2.3.5 worked fine and on the master the tool adressed 1.2.3.4 to check for existing records.

A --ipv4only option would also be a option if this is possible.

**Comment by verdel** [comment]
@mplaats

I added 3 command line arguments `--master-host`, `--master-port` and `--master-api-key'. The last two arguments are optional.

The default port is `8081`, just like `--port`.
The default value of the API key is the same as that of `--api-key`.

I will ask you to check the work of the new version of the script.

**Comment by mplaats** [comment]
Hi Verdel,

Thank you for the additional feature. I tested and everything is working perfect so this request case can be closed.
